deployment:
  imageURL: 784585544641.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
  imageVersion: 1.0.0

# statefulset:
#   imageURL: vamsi74507/catalogue
#   imageVersion: IMAGE_VERSION
hpa:
  maxReplicas: 10
  utilisation: 75